### ISSUE TITLE
Add buttons on column

### ISSUE THREAD

**Issue by VassilisPallas** [gbrock/laravel-table#14]
Hello, I want to add a column in my table which has buttons, eg, Show, Edit, Delete etc. Is this possible?

**Comment by gbrock** [comment]
Absolutely, just use a callback function:

```php
$table->addColumn('name', 'Name', function($model) {
    return '<a href="' . route('users.show', $model) . '">' . $model->name . '</a>';
});
```

**Comment by VassilisPallas** [comment]
Works like a charm! Thank you very much!
