### ISSUE TITLE
Create column with array fails

### ISSUE THREAD

**Issue by Blizzke** [gbrock/laravel-table#22]
Is it possible that you forget the `[0]` [here](https://github.com/gbrock/laravel-table/blob/master/src/Column.php#L43)?

`$class->setParameters($args);` should be `$class->setParameters($args[0]);` I think.
The way `setParameters` works, it expects keyed parameters, not numerical, which it gets like that. 

I call it like:

```
Table::create($models, [
   ['field' => 'field1', 'label' => 'Field 1 Label'],
   ['field' => 'field2', 'label' => 'Field 2 Label'],
 ]);
```

**Comment by gbrock** [comment]
You're right, that appears to be a bug.  Thanks for catching that.
