### ISSUE TITLE
Data outside db table

### ISSUE THREAD

**Issue by lloricode** [gbrock/laravel-table#23]
Is this possible to add data like `html button` with coressponding `id` of row?

**Comment by edwink75** [comment]
You could accomplish that with a custom render  method in your Model Class, ie:

```
    public function getRenderedIdAttribute($value){
        return '<a class="btn btn-default" href="link/to/display/'.$value.'">'.$value.'</a>';
    }
```

I personally stored my base link in the session as I make the whole row clickable and adjusted the view accordingly:

`session()->put('baselink', route('my.base.route'));`

and then in the view:

`<tr {!!session('baselink')!="" ? 'data-href="'.session('baselink').'/'.$r->id.'"' : ''!!}>`

Hope that helps someone.

**Comment by lloricode** [comment]
thanks @edwink75  :+1:
