### ISSUE TITLE
Using Query Builder instead of Eloquent model?

### ISSUE THREAD

**Issue by sunnyjayjay** [gbrock/laravel-table#3]
Is it possible to use a Query Builder instead of Eloquent model with this? I have tried and it fails. Basically I want to join tables in a dynamic query and get the results to display. But even something as simple as 

```
$rows = DB::table('users')->get(); 
$table = Table::create($rows); 
return view('reports.generic', ['table' => $table]);

``` 

falls over.

**Comment by gbrock** [comment]
This capability will be included in the next version.  Thanks for bringing it to my attention.

**Comment by sunnyjayjay** [comment]
Thanks. Do you have any idea of the timeframe for this?

**Comment by gbrock** [comment]
I went ahead and pushed this upstream from the new version so you can use it now.  It isn't sortable, but the [0.3.1](https://github.com/gbrock/laravel-table/releases/tag/0.3.1) release allows for basic rendering.

**Comment by sunnyjayjay** [comment]
Thanks. I downloaded your update and tried the example exactly as I posted at the start of this thread and it falls over with:
````
FatalErrorException in Table.php line 114:
Call to a member function first() on array
````

**Comment by gbrock** [comment]
It looks like you have an older version installed, but that wouldn't really have mattered since the version I directed you to was fully broken due to a typo.  I just pushed another update, so please make sure your composer.json is requesting `dev-master` or `0.3.2`.

**Comment by sunnyjayjay** [comment]
I have checked and I am using your latest version, I have compared Table.php line by line between my local copy and the version here on Github. But I get the error I posted above, that first() cannot be used on an array at line 114 in Table.php.

**Comment by gbrock** [comment]
OK, I've been digging deeper.  It looks like I was doing simple testing via a `$query->paginate()`, while the error occurs specifically with the standard `$query->get()`.  I just pushed [0.3.3](https://github.com/gbrock/laravel-table/releases/tag/0.3.3), please see if this works for your scenario.

**Comment by sunnyjayjay** [comment]
Thanks - that works a treat!
