### ISSUE TITLE
No sortable links in table headers L5.1

### ISSUE THREAD

**Issue by iNDicat0r** [gbrock/laravel-table#4]
It renders the Model properly but it doesn't include the clickable links in the table headers.
Laravel Framework version 5.1.20 

Thanks

**Comment by gbrock** [comment]
Have you added the columns to your model's `sortable` property?  Please post the table creation code.

**Comment by iNDicat0r** [comment]
Well in my user model i have the following:
    
use Sortable;
    /**
     * The attributes which may be used for sorting dynamically.
     *
     * @var array
     */
    protected $sortable = ['email', 'created_at'];

and in my controller:

$rows = User::sorted()->get();
$table = Table::create($rows, ['email', 'created_at']);
return view('admin.usersindex', ['table' => $table]);

and in admin.userindex:

{!! $table->render() !!}

**Comment by iNDicat0r** [comment]
The strange thing is that it properly renders the model without any errors. It just doesn't provide the sorting functionality. As you can see I have specified the sortable fields and what I want to include in the final table. The html which is produced in table headers are just text with the model column names and no links.

**Comment by iNDicat0r** [comment]
Solved the issue by changing the second setOptionsFromModel function in Column.php to: 

        if (property_exists($model, 'sortable') && $model->sortable && in_array($this->getField(),
                $model->getSortable())
        ) {
            // The model dictates that this column should be sortable
			
            $this->setSortable(true);
        }

and by defining the $sortable array in the User model as public and not protected ;)

Thanks!

**Comment by gbrock** [comment]
OK, I figured out what was happening.  I'm not sure why `property_exists($model, 'is_sortable')` was even there in the first place, but it was returning false, which broke functionality. Try using [0.3.4](https://github.com/gbrock/laravel-table/releases/tag/0.3.4).

And you can set your `$sortable` array(s) back to `protected` if you like; this is the package's declared access, but `public` works just as well.
