### ISSUE TITLE
how to get data from different model ?

### ISSUE THREAD

**Issue by 8lbiasian** [gbrock/laravel-table#6]
hello 

i have in my table Questions a field called language_id  which is the id of the language in the Languages table 
i want to get the name of that language through the id 

$table->addColumn('language_id', 'Language', function() {
          return Language::find(1)['Name'];
      });

so how i can pass the language_id to the find or any other way to get this =( 

thank you

**Comment by 8lbiasian** [comment]
$table->addColumn('language_id', 'Language', function($model) {

          return Questions::find($model->id)->language->Name;
      });

i try this but is there a better way ?

**Comment by hkan** [comment]
In case anybody else wants to know, here is how it's done:

```php
$table->addColumn('{put anything here, it wont even be used}', 'Column Label', function ($model)
{
    // Anything you return in this function will be used as the content of the column

    return $model->some_attribute;
});
```
